config/routes.rb
Rails.application.routes.draw do

  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  get "about" => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        post '/create_post' => 'topics#create_post', as: :create_post
      end
      resources :posts, only: [:index, :show, :destroy, :update]
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) {user ? all : publicly_viewable}
  scope :privately_viewable, -> {where(public: false)}
  scope :publicly_viewable, -> {where(public: true)}
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController

  before_filter :authenticate_user, except: [:index, :show]
  before_filter :authorize_user, except: [:index, :show, :create_post]

  def index
    topics = Topic.all
    render json: topics.to_json, status: 200
  end

  def show
    topic = Topic.find(params[:id])
    render json: topic.to_json, status: 200
  end

  def create
    topic = Topic.new(topic_params)

    if topic.valid?
      topic.save!
      render json: topic, status: 201
    else
      render json: {error: "Topic is invalid", status: 400}, status: 400
    end
  end

  def update
    topic = Topic.find(params[:id])

    if topic.update_attributes(topic_params)
      render json: topic, status: 200
    else
      render json: {error: "Topic update failed", status: 400}, status: 400
    end
  end

  def destroy
    topic = Topic.find(params[:id])

    if topic.destroy
      render json: {message: "Topic destroyed", status: 200}, status: 200
    else
      render json: {error: "Topic destroy failed", status: 400}, status: 400
    end
  end

  def create_post
    topic = Topic.find(params[:topic_id])
    post = topic.posts.build(post_params)
    post.user = @current_user

    if post.save
      render json: post, status: 200
    else
      render json: {error: "Post is invalid", status: 400}, status: 400
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_sign_in, except: [:index,:show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.visible_to(current_user)
  end

  def show
    @topic = Topic.find(params[:id])
    
    unless @topic.public || current_user
      flash[:error] = "You must be signed in to view private topics."
      redirect_to new_session_path
    end

  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      redirect_to @topic, notice: "Topic creaeted successfully"
    else
      flash[:error] = "There was an error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)
    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      redirect_to @topic, notice: "Topic updated successfully"
    else
      flash[:error] = "There was an error editing topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to topics_path, notice: "\"#{@topic.name}\" was deleted successfully"
    else
      flash[:error] = "There was an error deleting topic. Please try again."
      render :show
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
  def authorize_user
    unless current_user.admin?
      flash[:error] = "You must be an admin to do that"
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topic?
    current_user && current_user.admin?
  end
  def user_has_mod_privileges?
    current_user && (current_user.admin? || current_user.moderator?)
  end
end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>

  <% if topic.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
    <ul>
      <%= topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter topic name' %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description  %>
    <%= f.text_area :description, rows: 6, class: 'form-control', placeholder: 'Enter topic description' %>
  <% end %>
  <div class="form-group">
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to topic.name, topic %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter topic name' %>
    </div>
    <div class="form-group">
      <%= f.label :description  %>
      <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Enter topic description' %>
    </div>
    <div class="form-group">
      <%= render partial: 'labels/form', locals: {f: f, labels: @topic.labels } %>
    </div>
    <div class="form-group">
      <%= render partial: 'ratings/form', locals: {f: f, rating: @topic.rating} %>
    </div>
    <div class="form-group">
      <%= f.label :public, class: 'checkbox' do %>
        <%= f.check_box :public %> Public topic
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <%= render @topics %>
    <!-- <% @topics.each do |topic| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to topic.name, topic %>
        </h4>
        <small>
          <%= topic.description %>
        </small>
      </div>
    </div>
    <% end %> -->
  </div>
  <% if user_is_authorized_for_topic? %>
  <div class="col-md-4">
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter topic name' %>
    </div>
    <div class="form-group">
      <%= f.label :description  %>
      <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Enter topic description' %>
    </div>
    <!-- <div class="form-group"> -->
      <%= render partial: 'labels/form', locals: {f: f, labels: @topic.labels } %>

    <div class="form-group">
      <%= f.label :public, class: 'checkbox' do %>
        <%= f.check_box :public %> Public topic
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>
  <% end %>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
<% if user_is_authorized_for_topic? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?'} %>
<% end %>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
      <%= render partial: 'labels/list', locals: {labels: @topic.labels} %> <br />
      <%= @topic.description %>
    </p>
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= content_tag :div, id: "post-#{post.id}" do %>
          <%= render partial: 'votes/voter', locals: {post: post} %>
        <% end %>
        <div class="media-body">
          <h4 class"media-heading">
            <%= link_to post.title, topic_post_path(@topic, post) %>
            <%= render partial: 'labels/list', locals: {labels: post.labels} %>
          </h4>
          <small>
          submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
          <%= post.comments.count %> Comments
        </small>
        </div>
      </div>
    <% end %>
  </div>
  <% if current_user %>
  <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
  </div>
  <% end %>
</div>